# Generated by Django 4.2.4 on 2023-08-11 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicgear', '0002_alter_gear_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='category',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('G', 'Guitar'), ('K', 'Keyboard'), ('M', 'Microphone'), ('P', 'Pro Audio'), ('S', 'Software'), ('O', 'Other')], max_length=1)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicgear.gear')),
            ],
        ),
    ]
