# Generated by Django 4.2.4 on 2023-08-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicgear', '0003_remove_gear_category_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('gear', models.ManyToManyField(to='musicgear.gear')),
            ],
        ),
    ]
